CREATE TABLE IF NOT EXISTS "user" (
	"id" bigserial PRIMARY KEY NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"deleted_at" timestamp,
	"salt" text NOT NULL,
	"password" text NOT NULL,
	"password_reset_token" text,
	"password_reset_token_sent_at" timestamp,
	"password_reset_token_expired_at" timestamp,
	"email" varchar NOT NULL,
	"is_email_confirmed" boolean DEFAULT false NOT NULL,
	"email_confirm_token" varchar,
	"email_confirm_token_sent_at" timestamp,
	"email_update" varchar,
	"email_update_token" varchar,
	"email_update_token_sent_at" timestamp,
	"email_update_token_expired_at" timestamp,
	"phone" varchar NOT NULL,
	"is_phone_confirmed" boolean DEFAULT false NOT NULL,
	"phone_confirm_token" varchar,
	"phone_confirm_token_sent_at" timestamp,
	"phone_confirm_token_expired_at" timestamp,
	"phone_update" varchar,
	"phone_update_token" varchar,
	"phone_update_token_sent_at" timestamp,
	"phone_update_token_expired_at" timestamp,
	"last_name" varchar NOT NULL,
	"first_name" varchar NOT NULL,
	"gender" text NOT NULL,
	"timezone" text NOT NULL,
	"locale" text NOT NULL,
	"login_count" integer DEFAULT 0 NOT NULL,
	"last_login_at" timestamp
);
